apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ template "generate-name" (list . (dict "suffixname" "citrix-egress-hpa")) }} 
    namespace: {{ .Release.Namespace }}
spec:
    maxReplicas: 1
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: {{ template "generate-name" (list . (dict "suffixname" "egress-deployment")) }}
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 60
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "generate-name" (list . (dict "suffixname" "citrix-egress-svc")) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    app: {{ .Values.egressGateway.label | default "citrix-egressgateway" }}
{{- if eq .Values.citrixCPX true }}
    deployment: "cpx-egressgateway" # This label is useful in ServiceGraph
{{- end }}
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: {{ .Values.egressGateway.label | default "citrix-egressgateway" }}
---

{{- if eq .Values.citrixCPX false }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ template "generate-name" (list . (dict "suffixname" "citrix-egress-svcentry")) }}
spec:
  hosts:
  - {{ template "generate-name" (list . (dict "suffixname" "citrix-egress-svc")) }}.{{ .Release.Namespace }}.svc.cluster.local
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
  - address: {{ .Values.egressGateway.vserverIP }}
---
{{ end }}

