apiVersion: "citrix.com/v1beta1"
kind: globaltrafficpolicy
metadata:
  name: bookinfo
spec:
  serviceType: 'SSL'
  hosts:
  - host: 'bookinfo.appcluster.example.com'
    policy:
      trafficPolicy: 'ROUNDROBIN'
      targets:
      - destination: bookinfo.bookinfo.<region-1>.cluster1 #For eg: replace region-1 with eucentral
        weight: 50
      - destination:  bookinfo.bookinfo.<region-2>.cluster2 #For eg: replace region-2 with apnortheast
        weight: 50
      monitor:
      - monType: http
        uri: ''
        respCode: 200
