#This yaml applies Field Format Check on customer telephone number field in httpbin app's form
apiVersion: citrix.com/v1
kind: waf
metadata:
    name: httpbin
spec:
    target:
        header:
            - httpbin
    servicenames:
        - citrix-adc-istio-ingress-gateway-citrix-ingress-svc
    html_error_object: "local:error.html"
    security_checks:
        html:
          field_format: "on"
    enforcements:
        html:
          field_format:
            - rule:
                field_name: custtel
                url: "httpbin.appcluster.example.com/post"
                field_type: integer
                max_len: 10
